version: '3.8'

services:
  rescuelead-app:
    container_name: rescuelead-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/node_modules # mantém node_modules do container e evita conflito com node_modules do Windows
    networks:
      - rescuelead-network

networks:
  rescuelead-network:
    driver: bridge