services:
  php-server:
    image: php:8.2-apache
    container_name: php-server
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - rescuelead-network

  scraping-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scraping-bot
    restart: no
    env_file:
      - .env
    volumes:
      - .:/app
      # Esta linha cria um volume virtual para o node_modules interno do Docker (Linux)
      # e impede que ele tente ler pastas do Windows, resolvendo o erro ELF Header.
      - /app/node_modules
    networks:
      - rescuelead-network

networks:
  rescuelead-network:
    driver: bridge